# This file is managed by Terraform in infrahouse/github-control repository.
# Do not edit this file, all changes will be overwritten.
# If you need to add custom targets, create a new file in the makefiles/ directory.

SHELL := /usr/bin/env bash

.DEFAULT_GOAL := help
define PRINT_HELP_PYSCRIPT
import re, sys

for line in sys.stdin:
	match = re.match(r'^([a-zA-Z_-]+):.*?## (.*)$$', line)
	if match:
		target, help = match.groups()
		print("%-40s %s" % (target, help))
endef
export PRINT_HELP_PYSCRIPT

help: ## Print this help
	cat $(MAKEFILE_LIST) | python -c "$$PRINT_HELP_PYSCRIPT"

.PHONY: bootstrap
bootstrap: ## Build development environment
	pip install -r requirements.txt

.PHONY: lint
lint:  ## Check code style
	terraform fmt -check -recursive

.PHONY: format
format:  ## Format terraform files
	terraform fmt -recursive

.PHONY: init
init:
	terraform init

.PHONY: plan
plan: init ## Run terraform plan
	set -o pipefail ; terraform plan -no-color --out=tf.plan 2> plan.stderr | tee plan.stdout || (cat plan.stderr; exit 1)

.PHONY: apply
apply: ## Run terraform apply
	terraform apply -auto-approve -input=false tf.plan

.PHONY: smoke
smoke: ## Run post-deploy smoke test if scripts/smoke.sh exists
	@if [ -x scripts/smoke.sh ]; then \
		scripts/smoke.sh "$(ENV)"; \
	else \
		echo "smoke[$(ENV)]: no scripts/smoke.sh, skipping"; \
	fi

.PHONY: clean
clean: ## Remove generated files
	rm -fr .terraform
	rm -f .terraform.lock.hcl
	rm -f plan.stderr plan.stdout tf.plan
